"""empty message

Revision ID: e66ff0e49951
Revises: f9643ef029ee
Create Date: 2021-01-18 18:01:17.753411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e66ff0e49951'
down_revision = 'f9643ef029ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('todo', sa.Column('label', sa.String(length=120), nullable=False))
    op.drop_index('email', table_name='todo')
    op.create_unique_constraint(None, 'todo', ['label'])
    op.drop_column('todo', 'email')
    op.drop_column('todo', 'is_active')
    op.drop_column('todo', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('todo', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('todo', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'todo', type_='unique')
    op.create_index('email', 'todo', ['email'], unique=True)
    op.drop_column('todo', 'label')
    op.drop_column('todo', 'done')
    # ### end Alembic commands ###
